// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xrfrscsdrbxlqcgbzptp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZnJzY3NkcmJ4bHFjZ2J6cHRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNTY5OTUsImV4cCI6MjA3NjkzMjk5NX0.d_i799l8hWr1-Utg-eLdfS7La2o8at2xxoGACNiUv9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);