// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://slmwnuwuouetzjvwigdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsbXdudXd1b3VldHpqdndpZ2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MzY5MzMsImV4cCI6MjA3NDIxMjkzM30.eMa9NdmOoY5kBpo69NN9Rzn3FfmpvI5Gv0XevxQxsdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);